### ISSUE TITLE
Upgradable Starkvest contract

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#103]
**Description**
---
To prepare mainnet deployment and following regenesis, Starkvest  contract must be upgradable.

**Acceptance Criteria**
---

- [ ] All contracts are upgradables
- [ ] Updated Tests 
- [ ] Test the upgradable of the SC
- [ ] Scripts to upgrade contracts are available
