### ISSUE TITLE
Offseter new implementation : v2

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbonable-starknet#108]
**Description**
---
A new implementation version has been defined [here](https://app.excalidraw.com/l/4BTLOTSvKjp/76kEMPIGyah) which improve the solution from maintenance and UX pov.

**Acceptance Criteria**
---

- [ ] Solution is implemented
- [ ] Unit tests are implemented and run successfully
- [ ] Integration tests are implemented and run successfully
