### ISSUE TITLE
Yielder new implementation : v2

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbonable-starknet#115]
**Description**
---
A new implementation version has been defined [here](https://app.excalidraw.com/l/4BTLOTSvKjp/9I3wZ1s1H3G) which improve the solution from maintenance and UX pov.

**Acceptance Criteria**
---

- [x] Solution is implemented
- [x] Unit tests are implemented and run successfully
- [x] Integration tests are implemented and run successfully
