### ISSUE TITLE
[Yielder] Implement a function who return : How many NFTs are locked for a project ?

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#75]
**Description**
---
Implement a function to return the number of NFTs locked for a project to be Yield. 

**Acceptance Criteria**
---
- [x] Implement the function
- [x] Implement unit tests for each functions
- [x] Implement integration tests for each functions
- [x] If needed, write the documentation associated with the functions and events exposed

**Additional context**
---
excalidraw - [Farming schema](https://app.excalidraw.com/l/4BTLOTSvKjp/6YHFPM8REmR)
