### ISSUE TITLE
[Offseter] Implement the deposit of NFTs in a Farming Project Pool

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#76]
**Description**
---
Implement the deposit of NFTs, received after funding a Project, in a Farming Project Pool. 

Deposit one NFT by one NFT.

**Rules**
---
- Rule: A Carbonable NFT can be deposit only in a Yield farming OR an Offset farming pool per period
- Rule: The granularity in the Offseter is 1 Carbonable NFT

**Acceptance Criteria**
---
- [x] Implement the Rules
- [x] Implement unit tests for each functions
- [x] Implement integration tests for each functions
- [x] If needed, write the documentation associated with the functions and events exposed

**Additional context**
---
excalidraw - [Farming schema](https://app.excalidraw.com/l/4BTLOTSvKjp/6YHFPM8REmR)
