### ISSUE TITLE
[Offseter] Implement a function : Which percentage (%) of Carbon Credit of a Project I have for my address ?

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#79]
**Description**
---
Implement a function which:
Give the percentage (%) of Carbon Credit of a Project, for a given address, is entitled to receive for the current period.

This function calculates the number of NFTs deposited by the address and returns the amount of Carbon Credit it will receive for this period for this Project. 

**Acceptance Criteria**
---
- [x] Implement the function
- [x] Implement unit tests for each functions
- [ ] Implement integration tests for each functions
- [x] If needed, write the documentation associated with the functions and events exposed

**Additional context**
---
excalidraw - [Farming schema](https://app.excalidraw.com/l/4BTLOTSvKjp/6YHFPM8REmR)
