### ISSUE TITLE
[Yielder] Implement the retrieve function of NFTs from a Farming Project Pool during the unlock period

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#80]
**Description**
---
Implement the retrieve of NFTs from a Farming Project Pool during the unlock period

**Rules**
---
- Rule: A Carbonable NFT can be retrieved only from a Yield farming OR an Offset farming pool per period
- Rule: The granularity in the Yielder is 1 Carbonable NFT

**Acceptance Criteria**
---
- [x] Implement the Rules
- [x] Implement unit tests for each functions
- [x] Implement integration tests for each functions
- [x] If needed, write the documentation associated with the functions and events exposed

**Additional context**
---
excalidraw - [Farming schema](https://app.excalidraw.com/l/4BTLOTSvKjp/6YHFPM8REmR)
