### ISSUE TITLE
[Yielder] Upgrade Starkvest as Cairo 0.10.1 on the official repo

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#83]
**Description**
---
Upgrade  [Starkvest contract](https://github.com/abdelhamidbakhta/starkvest) into Cairo 0.10.1 

**Acceptance Criteria**
---
- [x] Implement unit tests for each functions
- [x] Implement integration tests for each functions
- [x] If needed, write the documentation associated with the functions and events exposed

**Comment by cloudvenger** [comment]
PR on abdel repo of starkvest 

https://github.com/abdelhamidbakhta/starkvest/pull/3
