### ISSUE TITLE
[Yielder] Expand tests coverage on Starkvest to cover Carbonable functional scope

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#88]
**Description**
---
Expand tests coverage on Starkvest to cover Carbonable functional scope

[Starkvest](https://github.com/abdelhamidbakhta/starkvest)

**Acceptance Criteria**
---
- [x] Implement unit tests for each functions
- [x] Implement integration tests for each functions
- [ ] If needed, write the documentation associated with the functions and events exposed
