### ISSUE TITLE
Upgradable contracts

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbonable-starknet#90]
**Description**
---
To prepare mainnet deployment and following regenesis, all our contracts must be upgradable.

Next step: 
- Upgrade all our contracts to make them upgradable 
- Take the opportunity to make them breakable (with owner wallet) and better manage the ownership of projects #58 
- Update the CI/CD to set up deployments as a proxy
- Set up the tests and test the upgrades on the testnet

**Acceptance Criteria**
---

- [ ] All contracts are upgradables
- [ ] CI/CD is updated to deploy through proxy
- [ ] Updated Tests 
- [ ] Test the upgradable of the SC
- [ ] Scripts to upgrade contracts are available

**Comment by cloudvenger** [comment]
See Medium article [StarkNet Guide: Writing Upgradable Contracts using a Proxy](https://medium.com/@EmpiricNetwork/starknet-guide-writing-upgradable-contracts-using-a-proxy-af3f107f238b)
