### ISSUE TITLE
[Offseter] Implement count view instead of share

### ISSUE THREAD

**Issue by Bal7hazar** [Carbonable/carbonable-starknet#92]
**Description**
---
Share quantity does not have much sense for Offseter contract, we should implement a counter instead.
This view returns a number of token locked by a user (instead of its share).

**Acceptance Criteria**
---

- [x] Feature is implemented
- [x] Associated unit tests are implemented
- [x] Associated integration tests are implemented
- [x] Documentation is updated

**Comment by Bal7hazar** [comment]
Done in #72
