### ISSUE TITLE
Farming Offset counter management

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#93]
**Description**
---
Implement 2 function: 
- From an admin/owner call on Offseter Smart Contract, execute an external function, call `snaptshot` function which snaptshot and increment amount of carbon credit (`total_offsetable`) each user have deposited in the farming Pool and send an event. 

- From a caller, on Offseter Smart Contract, execute an external function, call `offset` function which reset the amount of carbon credit (`total_offsetable`) for the caller and send an event. 

**Acceptance Criteria**
---

- [x]  Implement unit tests for each functions
- [x]  Implement integration tests for each functions
- [x]  If needed, write the documentation associated with the functions and events exposed
