### ISSUE TITLE
Upgrade deployment of Smart Contract on CI/CD through Proxy (Uprgadable)

### ISSUE THREAD

**Issue by cloudvenger** [Carbonable/carbonable-starknet#98]
**Description**
---
Update the CI/CD to set up deployments as a proxy for all SC. 

**Acceptance Criteria**
---
- [x] Test the upgradable of the SC
- [x] CI/CD is updated to deploy through proxy
- [x] CI/CD is on testnet (define if it's testnet-1 or testnet-2 or both)

**Comment by cloudvenger** [comment]
Deployed on :
- Alpha test (Helper + team) : testnet-2
- Beta test (Commu) : testnet-1
